### ISSUE TITLE
Fatal error: Class 'hypeJunction\Lists\ElggList' not found

### ISSUE THREAD

**Issue by Yaco** [hypeJunction/hypeMaps#4]
I get this error when I try to load `/maps` url:

`Fatal error: Class 'hypeJunction\Lists\ElggList' not found in /srv/elgg/mod/hypeMaps/classes/hypeJunction/Maps/ElggMap.php on line 9`

I installed HypeLists, just in case. Didn't work. 

Any clue or fix?

**Comment by hypeJunction** [comment]
Try running composer install from plugin root

**Comment by Yaco** [comment]
Thanks @hypeJunction, it worked!
